name: (Procedure) Release API reference (nightly)
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check-code-update:
    runs-on: ubuntu-20.04
    outputs:
      abort: ${{ steps.set-output.outputs.abort }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: set-output
        name: Check if the code or workflows has been changed.
        run: |
          if [ $(git --no-pager diff --name-only HEAD^ vkit | wc -l) -eq 0 ] \
              && [ $(git --no-pager diff --name-only HEAD^ .github | wc -l) -eq 0 ]
          then
            echo "abort=1" >> $GITHUB_OUTPUT
          else
            echo "abort=0" >> $GITHUB_OUTPUT
          fi
  call-workflow-publish-api-reference:
    uses: ./.github/workflows/workflow-publish-api-reference.yaml
    needs: check-code-update
    if: needs.check-code-update.outputs.abort != 1
    with:
      github-page-repo: "vkit-x/vkit-api-reference-github-page"
      nightly: true
      domain: "vkit-api-reference.vkit-x.com"
    secrets:
      github-page-repo-deploy-key: ${{ secrets.VKIT_API_REFERENCE_GITHUB_PAGE_DEPLOY_KEY }}
