name: Publish to GitHub Page
on:
  workflow_call:
    inputs:
      website-repo:
        required: true
        type: string
      website-data-repo:
        required: true
        type: string
      github-page-repo:
        required: true
        type: string
      domain:
        required: true
        type: string
    secrets:
      github-page-repo-deploy-key:
        required: true
jobs:
  publish-to-github-page:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install ssh-agent
        run: |
          sudo apt-get install -y openssh-client
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.github-page-repo-deploy-key }}
      - name: Download website repo and website-data repo
        run: |
          rm -rf .git

          # Download website repo.
          git clone git@github.com:${{ inputs.website-repo }}.git website
          rm -rf website/.git

          # Copy docs.
          cp -r docs/* website/

          # Download resource.
          cd website
          git clone git@github.com:${{ inputs.website-data-repo }}.git website-data
          find website-data \
            -maxdepth 1 -type d \
            -not -path website-data \
            -not -path '*.git' \
            -exec mv {} $(realpath static)/ \;
          rm -rf website-data
      - name: Build and publish
        run: |
          cd website

          # Configure domain for docusaurus.
          SED_PATTERN="s|url: 'CHANGE_ME'|url: 'https://${{ inputs.domain }}'|g"
          sed -i "$SED_PATTERN" docusaurus.config.js

          node -v
          yarn --version

          yarn install
          yarn run build

          cd build

          # Configure domain for github page.
          echo "${{ inputs.domain }}" > CNAME

          git config --global user.email "huntzhan.dev@gmail.com"
          git config --global user.name "Hunt Zhan"

          git init
          git add --all
          git commit -m "Published by GitHub Action."

          git remote add origin git@github.com:${{ inputs.github-page-repo }}.git
          git push -u origin master --force
