name: release-website-stable
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm'
        required: true
jobs:
  check-stable-version-update:
    runs-on: ubuntu-20.04
    outputs:
      abort: ${{ steps.set-output.outputs.abort }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: set-output
        name: Check if the website has been changed.
        run: |
          if [ $(git --no-pager diff HEAD^ setup.cfg | grep +version | wc -l) -ne 0 ] \
              && [ $(git --no-pager diff HEAD^ setup.cfg | grep +version | grep a | wc -l) -eq 0 ] \
              && [ $(git --no-pager diff HEAD^ setup.cfg | grep +version | grep b | wc -l) -eq 0 ] \
              && [ $(git --no-pager diff HEAD^ setup.cfg | grep +version | grep rc | wc -l) -eq 0 ]
          then
            echo "::set-output name=abort::0"
          else
            echo "::set-output name=abort::1"
          fi
  call-publish-to-github-page:
    uses: ./.github/workflows/publish-to-github-page.yaml
    needs: check-stable-version-update
    if: needs.check-stable-version-update.outputs.abort != 1 || github.event.inputs.confirm == 'yes'
    with:
      website-repo: "vkit-x/vkit-website"
      website-data-repo: "vkit-x/vkit-website-data"
      github-page-repo: "vkit-x/vkit-website-github-page"
      domain: "vkit.vkit-x.com"
    secrets:
      github-page-repo-deploy-key: ${{ secrets.GH_PAGE_STABLE_REPO_KEY }}
