name: release-website-nightly
on:
  push:
    branches:
      - master
jobs:
  check-website-update:
    runs-on: ubuntu-20.04
    outputs:
      abort: ${{ steps.set-output.outputs.abort }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: set-output
        name: Check if the website has been changed.
        run: |
          if [ $(git --no-pager diff --name-only HEAD^ website | wc -l) -eq 0 ]  \
              && [ $(git --no-pager diff --name-only HEAD^ .github | wc -l) -eq 0 ]
          then
            echo "::set-output name=abort::1"
          else
            echo "::set-output name=abort::0"
          fi
  call-publish-to-github-page:
    uses: ./.github/workflows/publish-to-github-page.yaml
    needs: check-website-update
    if: needs.check-website-update.outputs.abort != 1
    with:
      website-repo: "vkit-x/vkit-website"
      website-data-repo: "vkit-x/vkit-website-data"
      github-page-repo: "vkit-x/vkit-website-nightly-github-page"
      domain: "vkit-nightly.vkit-x.com"
    secrets:
      github-page-repo-deploy-key: ${{ secrets.VKIT_WEBSITE_NIGHTLY_GITHUB_PAGE_DEPLOY_KEY }}
