name: schedule
on:
  schedule:
    - cron: "0 */1 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  call-type-checking:
    uses: ./.github/workflows/type-checking.yaml
  call-test:
    uses: ./.github/workflows/test.yaml
