name: (Workflow) Alarm
on:
  workflow_call:
    inputs:
      send-alarm:
        required: true
        type: boolean
      message:
        required: true
        type: string
    secrets:
      webhook-url:
        required: true
jobs:
  alarm:
    runs-on: ubuntu-20.04
    if: ${{ inputs.send-alarm }}
    steps:
      - name: Send alarm.
        run: |
          echo "Something is wrong, send alarm."
          PAYLOAD=$(
          cat << EOF

          {
              "msgtype": "text",
              "text": {
                  "content": "${{ inputs.message }}"
              }
          }

          EOF
          )
          curl "${{ secrets.webhook-url }}" -H 'Content-Type: application/json' -d "$PAYLOAD"

          # Mark the github action run as failed.
          exit 1
